development:
  adapter: postgresql
  database: westlawn_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: westlawn_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: westlawn_production
  pool: 5
  timeout: 5000
